csv_train_data: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSyB_kQrfmaoG2nwsE0DbOMnyNbFUyH9IDKBJhR8yo4JdGAcLSTS1NTC2_Z4BIbwnRuIg58WChttoWa/pub?gid=1835661926&single=true&output=csv'
lstm0_units: 10
lstm1_units: 20
lstm2_units: 30

lag: 12
points_per_call: 16

dropout_count: 0.0
dense_units: 30
activation: 'relu'
#activation: 'tanh'

optimizer: 'adam'
epochs: 3
