csv_train_data: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRFF6SXvGbQgQG1bh0hwbXgVWpUU_UG8OQAVhHcNAcAFT5x-XoIYxMAeF-goym6_wNhJEwQd3iGHp9b/pub?gid=791211028&single=true&output=csv'
cnn0_units: 64
cnn1_units: 128
lstm0_units: 30
lstm1_units: 20
lstm2_units: 10
lag: 4
points_per_call: 16
regularizers_l2: 0.2
recurrent_dropout_rate: 0.2
activation: 'relu'
optimizer: 'adam'
epochs: 3
